(define-constant module-description '(
  (gauche.array . "Arrays")
  (gauche.charconv . "Character Code Conversion")
  (gauche.cgen . "Generating C Code")
  (gauche.collection . "Collection framework")
  (gauche.config . "Configuration parameters")
  (gauche.dictionary . "Dictionary framework")
  (gauche.fcntl . "Low-level file operations")
  (gauche.generator . "Generators")
  (gauche.hook . "Hooks")
  (gauche.interactive . "Utilities for interactive session")
  (gauche.lazy . "Lazy sequence utilities")
  (gauche.listener . "Listener")
  (gauche.logger . "User-level logging")
  (gauche.mop.propagate . "Propagating slot access")
  (gauche.mop.singleton . "Singleton")
  (gauche.mop.validator . "Slot with validator")
  (gauche.net . "Networking")
  (gauche.parameter . "Parameters")
  (gauche.parseopt . "Parsing command-line options")
  (gauche.partcont . "Partial continuations")
  (gauche.process . "High Level Process Interface")
  (gauche.record . "Record types")
  (gauche.reload . "Reloading modules")
  (gauche.selector . "Simple dispatcher")
  (gauche.sequence . "Sequence framework")
  (gauche.syslog . "Syslog")
  (gauche.termios . "Terminal control")
  (gauche.test . "Unit Testing")
  (gauche.threads . "Threads")
  (gauche.time . "Measure timings")
  (gauche.uvector . "Uniform vectors")
  (gauche.version "Comparing version numbers")
  (gauche.vport . "Virtual ports")
  (srfi-0 . "Feature conditional")
  (srfi-1 . "List Library")
  (srfi-4 . "Homogeneous vectors")
  (srfi-5 . "A compatible let form with signatures and rest arguments")
  (srfi-7 . "Let-values")
  (srfi-13 . "String library")
  (srfi-14 . "Character-set library")
  (srfi-19 . "Time data types and procedures")
  (srfi-27 . "Sources of Random Bits")
  (srfi-29 . "Localization")
  (srfi-37 . "args-fold a program argument processor")
  (srfi-42 . "Eager comprehensions")
  (srfi-43 . "Vector library")
  (srfi-55 . "Requiring extensions")
  (srfi-60 . "Integers as bits")
  (srfi-98 . "Accessing environment variables")
  (binary.io . "Binary I/O")
  (binary.pack . "Packing Binary Data")
  (compat.norational . "Rational-less arithmetic")
  (control.job . "A common job descriptor for control modules")
  (control.thread-pool . "Thread pools")
  (crypt.bcrypt . "Password hashing")
  (dbi . "Database independent access layer")
  (dbm . "Generic DBM interface")
  (dbm.fsdbm . "File-system dbm")
  (dbm.gdbm . "GDBM interface")
  (dbm.ndbm . "NDBM interface")
  (dbm.odbm . "Original DBM interface")
  (file.filter . "Filtering file content")
  (file.util . "Filesystem utilities")
  (math.const . "Mathematic constants")
  (math.mt-random . "Mersenne Twister Random number generator")
  (os.windows . "Windows  support")
  (rfc.822 . "RFC822 message parsing")
  (rfc.base64 . "Base64 encoding/decoding")
  (rfc.cookie . "HTTP cookie handling")
  (rfc.ftp . "FTP client")
  (rfc.hmac . "HMAC keyed-hashing")
  (rfc.http . "HTTP")
  (rfc.ip . "IP packets")
  (rfc.icmp . "ICMP packets")
  (rfc.json . "JSON parsing and construction")
  (rfc.md5 . "MD5 message digest")
  (rfc.mime . "MIME message handling")
  (rfc.quoted-printable . "Quoted-printable encoding/decoding")
  (rfc.sha . "SHA message digest")
  (rfc.uri . "URI parsing and construction")
  (rfc.zlib . "zlib compression library")
  (slib . "SLIB interface")
  (sxml.ssax . "Functional XML parser")
  (sxml.sxpath . "SXML Query Language")
  (sxml.tools . "Manipulating SXML structure")
  (sxml.serializer . "Serializing XML and HTML from SXML")
  (text.csv . "CSV tables")
  (text.diff . "Calculate difference of text streams")
  (text.gettext . "Localized messages")
  (text.html-litle . "Simple HTML document construction")
  (text.parse . "Parsing input stream")
  (text.progress . "Showing progress on text terminals")
  (text.sql . "SQL parsing and construction")
  (text.tr . "Transliterate characters")
  (text.tree . "Lazy text construction")
  (text.unicode . "Unicode utilities")
  (util.combinations . "Combination library")
  (util.digest . "Messae digester frameworks")
  (util.isomorph . "Determine isomorphism")
  (util.lcs . "The longest common subsequence")
  (util.match . "Patterm matching")
  (util.queue . "Queue")
  (util.rbtree . "Red black tree")
  (util.record . "SLIB-compatible record type")
  (util.relation . "Relation framework")
  (util.sparse . "Sparse data containers")
  (util.stream . "Stream library")
  (util.trie . "Trie")
  (util.toposort . "Topological sort")
  (www.cgi . "CGI utility")
  (www.cgi.test . "CGI testing")
  ))

